### ISSUE TITLE
Memory leak on AppEngineToolsMenuAction.actionPerformed()

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1005]
Not too sure how I triggered this state, but saw this memory leak possibly caused by AppEngineToolsMenuAction.actionPerformed.

[ 195559]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: com.intellij.openapi.options.SettingsEditorGroup@21597ca of class class com.intellij.openapi.options.SettingsEditorGroup
See the cause for the corresponding Disposer.register() stacktrace:

java.lang.RuntimeException: Memory leak detected: com.intellij.openapi.options.SettingsEditorGroup@21597ca of class class com.intellij.openapi.options.SettingsEditorGroup
See the cause for the corresponding Disposer.register() stacktrace:

```
at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:209)
at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:124)
at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:120)
at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:308)
at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:859)
at com.intellij.openapi.application.impl.ApplicationImpl.access$1000(ApplicationImpl.java:91)
at com.intellij.openapi.application.impl.ApplicationImpl$17.run(ApplicationImpl.java:835)
at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:841)
at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:790)
at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:785)
at com.intellij.openapi.wm.impl.IdeFrameImpl$5$1.run(IdeFrameImpl.java:273)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:866)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Caused by: java.lang.Throwable
    at com.intellij.openapi.util.objectTree.ObjectTree.getOrCreateNodeFor(ObjectTree.java:101)
    at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:62)
    at com.intellij.openapi.util.Disposer.register(Disposer.java:80)
    at com.intellij.openapi.util.Disposer.register(Disposer.java:74)
    at com.intellij.openapi.options.SettingsEditor.<init>(SettingsEditor.java:56)
    at com.intellij.openapi.options.SettingsEditor.<init>(SettingsEditor.java:51)
    at com.intellij.openapi.options.SettingsEditorGroup.<init>(SettingsEditorGroup.java:26)
    at com.intellij.remoteServer.impl.configuration.deployment.DeployToServerRunConfiguration.getConfigurationEditor(DeployToServerRunConfiguration.java:89)
    at com.intellij.execution.impl.ConfigurationSettingsEditor.<init>(ConfigurationSettingsEditor.java:220)
    at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.<init>(ConfigurationSettingsEditorWrapper.java:67)
    at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:65)
    at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:99)
    at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:121)
    at com.intellij.remoteServer.impl.configuration.deployment.DeploymentConfigurationManagerImpl.createAndRunConfiguration(DeploymentConfigurationManagerImpl.java:63)
    at com.google.cloud.tools.intellij.appengine.cloud.AppEngineToolsMenuAction.actionPerformed(AppEngineToolsMenuAction.java:66)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    ... 7 more

**Comment by patflynn** [comment]
I wonder why this isn't being configured in the plugin.xml instead of the
CloudToolsPluginInitializationComponent.

**Comment by etanshaul** [comment]
@joaoandremartins just curious - did you notice this leak in the logs after you shut down the IDE or while it was still open?

**Comment by joaoandremartins** [comment]
While it was open. I noticed it a second time later in the day, too.

I'll try to add more detail here if I can reproduce..

**Comment by etanshaul** [comment]
Not reproducible
