### ISSUE TITLE
Cannot start dev_appserver

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#1044]
After creating a project using the new project wizard, the dev_appserver does not start, and gives no output. After stopping the dev_appserver, the following output is dumped:

```
Running dev_appserver.py.
Traceback (most recent call last):
  File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 89, in <module>
    _run_file(__file__, globals())
  File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 85, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
    main()
  File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
    dev_server.start(options)
Allow dev_appserver to check for updates on startup? (Y/n):   File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 771, in start
    update_checker.check_for_updates(configuration)
  File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/update_checker.py", line 91, in check_for_updates
    if update_check.AllowedToCheckForUpdates():
  File "/usr/local/google/home/alexsloan/tools/google-cloud-sdk/platform/google_appengine/google/appengine/tools/sdk_update_checker.py", line 408, in AllowedToCheckForUpdates
    answer = input_fn('Allow dev_appserver to check for updates on startup? '
EOFError: EOF when reading a line
Terminating dev_appserver.py.
Disconnected from server

```

**Comment by patflynn** [comment]
for reference:
b/32275943
