### ISSUE TITLE
Could not load Logmanager "org.apache.logging.log4j.jul.LogManager

### ISSUE THREAD

**Issue by originalrusyn** [GoogleCloudPlatform/google-cloud-intellij#1073]
Google Cloud SDK 131.0.0
app-engine-java 1.9.44
app-engine-python 1.9.40
beta 2016.01.12
bq 2.0.24
bq-win 2.0.24
bundled-python 2.7.10
core 2016.10.17
core-win 2016.08.05
gcloud
gsutil 4.21
gsutil-win 4.20
powershell 0.1.8
windows-ssh-tools 2016.05.13

jdk 1.8.111

Just run https://github.com/originalrusyn/credits2/tree/googleCloudPlatformIdeaPlugin with Google App Engine Local Development Server plugin for Intellij Idea with 

-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager

and open localhost:8080/

`Could not load Logmanager "org.apache.logging.log4j.jul.LogManager"
java.lang.ClassNotFoundException: org.apache.logging.log4j.jul.LogManager
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.util.logging.LogManager$1.run(LogManager.java:195)
    at java.util.logging.LogManager$1.run(LogManager.java:181)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.util.logging.LogManager.<clinit>(LogManager.java:181)
    at java.util.logging.Logger.demandLogger(Logger.java:448)
    at java.util.logging.Logger.getLogger(Logger.java:502)
    at com.google.appengine.tools.development.devappserver2.StandaloneInstance.<clinit>(StandaloneInstance.java:35)`

**Comment by etanshaul** [comment]
obsolete
