### ISSUE TITLE
crash: user reported error during appengine-web.xml detection

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1076]
com.jetbrains.django.lang.template.psi.impl.DjangoTemplateFileImpl cannot be cast to com.intellij.psi.xml.XmlFile

Exception class name: java.lang.ClassCastException: com.jetbrains.django.lang.template.psi.impl.DjangoTemplateFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
Exception message: com.jetbrains.django.lang.template.psi.impl.DjangoTemplateFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
Stack trace:
java.lang.ClassCastException: com.jetbrains.django.lang.template.psi.impl.DjangoTemplateFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
    at com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineAssetProvider.loadAppEngineStandardWebXml(DefaultAppEngineAssetProvider.java:72)
    at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck$1.run(AppEngineStandardUnsupportedJavaVersionCheck.java:81)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
    at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.findAppEngineModulesUsingUnsupportedLanguageLevel(AppEngineStandardUnsupportedJavaVersionCheck.java:73)
    at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.runActivity(AppEngineStandardUnsupportedJavaVersionCheck.java:63)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:146)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:344)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:160)
    at com.intellij.openapi.project.DumbServiceImpl.b(DumbServiceImpl.java:343)
    at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
    at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
    at com.intellij.openapi.project.DumbServiceImpl.b(DumbServiceImpl.java:322)
    at com.intellij.openapi.project.DumbServiceImpl.e(DumbServiceImpl.java:304)
    at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
    at com.intellij.openapi.project.DumbServiceImpl.d(DumbServiceImpl.java:303)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:76)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Signal:
Throw file name: DefaultAppEngineAssetProvider.java
Throw line number: 72
Throw class name: com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineAssetProvider
Throw method name: loadAppEngineStandardWebXml

IntelliJ IDEA 2016 EAP 3
Mac OS X
plugin.version  
16.10.5

**Comment by etanshaul** [comment]
This is a weird one. I think I'll expand the error logging around this so that we can get a better idea if this happens again. Somehow this django config file was found when search for appengine-web.xml's (by name).

**Comment by etanshaul** [comment]
error logging improved. bug not seen anymore
