### ISSUE TITLE
user reported Project Selector error in IJ 2016.3.4

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1202]
```
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.resources.GoogleUserModelItem$3.compare(GoogleUserModelItem.java:155)
	at com.google.cloud.tools.intellij.resources.GoogleUserModelItem$3.compare(GoogleUserModelItem.java:152)
	at java.util.TreeMap.put(TreeMap.java:552)
	at java.util.TreeSet.add(TreeSet.java:255)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.TreeSet.addAll(TreeSet.java:312)
	at com.google.cloud.tools.intellij.resources.GoogleUserModelItem.loadUserProjects(GoogleUserModelItem.java:158)
	at com.google.cloud.tools.intellij.resources.GoogleUserModelItem.access$000(GoogleUserModelItem.java:53)
	at com.google.cloud.tools.intellij.resources.GoogleUserModelItem$1.run(GoogleUserModelItem.java:117)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by patflynn** [comment]
os.name	
Mac OS X
plugin.version	
16.11.6

**Comment by patflynn** [comment]
this is the code from the v16.11.6 tag

```
        Set<Project> allProjects = new TreeSet<Project>(new Comparator<Project>() {
          @Override
          public int compare(Project p1, Project p2) {
            return p1.getName().toLowerCase().compareTo(p2.getName().toLowerCase());
          }
        });
```

**Comment by patflynn** [comment]
presumably an error in the response or the data?  I can't reproduce so I'm moving a fix out of this release.
