### ISSUE TITLE
Error running local dev appserver on Windows

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1214]
Steps to reproduce:

On Windows 10:

1) File -> New project from Version Control -> Git
2) URL = https://github.com/patflynn/hello-world-appengine-std.git
3) Import and enable maven sync and add framework support for appengine and web from the notification
4) run the dev server run config
5) see the run config editor pop up
6) select the module artifact
7) click run
8) observe
<img width="928" alt="null" src="https://cloud.githubusercontent.com/assets/7862557/22708365/009a21b6-ed44-11e6-9789-f418107c0822.png">
9) from logs
```
elliJIdea2016.3\config -Didea.plugins.path=C:\Users\cloud-sdk\.IntelliJIdea2016.3\config\plugins -Djps.log.dir=C:/Users/cloud-sdk/.IntelliJIdea2016.3/system/log/build-log -Djps.fallback.jdk.home=C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/jre/jre -Djps.fallback.jdk.version=1.8.0_112-release -Djava.io.tmpdir=C:/Users/cloud-sdk/.IntelliJIdea2016.3/system/compile-server/_temp_ -Dkotlin.incremental.compilation.experimental=true -Dkotlin.daemon.enabled -Dkotlin.daemon.client.alive.path=\"C:\Users\CLOUD-~1\AppData\Local\Temp\kotlin-idea-2853288925666596166-is-running\" -classpath C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jps-launcher.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/jre/lib/tools.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/optimizedFileManager.jar org.jetbrains.jps.cmdline.Launcher C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/log4j.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/javac2.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/protobuf-2.5.0.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jdom.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/openapi.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/trove4j.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jps-model.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/forms_rt.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jna-platform.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jgoodies-forms.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/oromatcher.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jna.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/asm-all.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/annotations.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/util.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/netty-all-4.1.5.Final.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/snappy-in-java-0.5.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/resources_en.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/rt/jps-plugin-system.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jps-builders.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/nanoxml-2.2.3.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/idea_rt.jar;;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/commons-io-2.2.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/commons-lang-2.6.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-base-services-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-base-services-groovy-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-cli-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-core-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-logging-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-messaging-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-model-core-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-model-groovy-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-native-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-process-services-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-resources-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-tooling-api-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-tooling-extension-api.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-tooling-extension-impl.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-wrapper-3.1.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/guava-jdk5-17.0.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/jsr305-1.3.9.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/kryo-2.22.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/minlog-1.2.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-freebsd-amd64-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-freebsd-i386-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-linux-amd64-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-linux-i386-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-osx-amd64-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-osx-i386-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-windows-amd64-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/native-platform-windows-i386-0.11.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/objenesis-1.2.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/reflectasm-1.07.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/resources_en.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/gson-2.5.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/jarutils.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/ant/lib/ant-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/devkit/lib/devkit-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/uiDesigner/lib/jps/ui-designer-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/IntelliLang/lib/intellilang-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Groovy/lib/groovy-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Groovy/lib/groovy-rt-constants.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/eclipse/lib/eclipse-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/eclipse/lib/common-eclipse-util.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/maven/lib/maven-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/maven/lib/aether-dependency-resolver.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/maven/lib/aether-1.1.0-all.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/maven/lib/maven-aether-provider-3.3.9-all.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/maven/lib/plexus-utils-2.0.6.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/osmorc/lib/osmorc-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/osmorc/lib/bndlib-3.3.0.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/osmorc/lib/bnd-repository-3.3.0.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/osmorc/lib/bnd-resolve-3.3.0.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/osmorc/lib/plexus-utils-3.0.10.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/osmorc/lib/bundlor-all.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/aspectj/lib/aspectj-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/flex/lib/flex-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/flex/lib/flex-shared.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/gradle/lib/gradle-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/JavaEE/lib/javaee-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/JavaEE/lib/jps/jpa-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/webSphereIntegration/lib/jps/webSphere-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/weblogicIntegration/lib/jps/weblogic-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/dmServer/lib/dmServer-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/GwtStudio/lib/gwt-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Grails/lib/grails-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Grails/lib/grails-compiler-patch.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/jps/android-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/jps/android-gradle-jps.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/android-common.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/android-rt.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/sdk-common.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/repository.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/sdklib.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/common.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/jarutils.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/layoutlib-api.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/android/lib/manifest-merger.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Kotlin/lib/jps/kotlin-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Kotlin/lib/kotlin-runtime.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Kotlin/lib/kotlin-reflect.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Kotlin/lib/kotlin-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Kotlin/lib/kotlin-android-extensions-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/Kotlin/lib/kotlin-android-extensions-compiler-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/javaFX/lib/javaFX-jps-plugin.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/plugins/javaFX/lib/common-javaFX-plugin.jar org.jetbrains.jps.cmdline.BuildMain 127.0.0.1 50956 31ec26a9-b0d3-446d-b014-9e1aeed321a7 C:/Users/cloud-sdk/.IntelliJIdea2016.3/system/compile-server 
2017-02-07 14:38:24,732 [1456884]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/jps-launcher.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/jre/lib/tools.jar;C:/Users/cloud-sdk/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/163.12024.16/lib/optimizedFileManager.jar 
2017-02-07 14:38:25,443 [1457595]   INFO - ee.run.state.PatchedLocalState -  
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.appengine.server.instance.AppEngineServerModel.getJavaHomeDir(AppEngineServerModel.java:437)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer.run(CloudSdkAppEngineDevServer.java:72)
	at com.google.cloud.tools.intellij.appengine.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:66)
	at com.google.cloud.tools.intellij.appengine.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:37)
	at com.google.cloud.tools.intellij.appengine.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartupPolicy.java:97)
	at com.intellij.javaee.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:76)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by etanshaul** [comment]
I wasn't able to reproduce this

**Comment by patflynn** [comment]
since the bug appears to be related to the java home dir config, I'm guessing this happens in conjunction with a specific configuration of the project SDK.

**Comment by joaoandremartins** [comment]
Actually, I think you're seeing another bug which is a bit dissimulated. (At least, I'm seeing the same thing in Windows)

When you press the Start button for the first time, the run config editor is not supposed to pop up. It should only do so when in error state.

With me, there was no JDK set in the project and the run config was in an error state. However, when I press run and the run config editor pops up, there is no error messaging anywhere, so I press run, but I still get warned that the config is in error state. If I try to run it anyway, I'm finally warned that no JDK is set in the module.

After setting the JDK, though, I'm still seeing the run config in error state, but I can run it without an issue.

This didn't happen for you project, but one of mine. I couldn't reproduce your issue. I was having issues with a cached older version of the common library, did you try cleaning and refreshing the Gradle plugin project?

In this specific case, devAppServerJdk isn't being set and an NPE is bring thrown because of that.

**Comment by patflynn** [comment]
I discovered that the module JDK was configured but the Project SDK is not set. But I should be getting an error for that when I try to start the server.

**Comment by patflynn** [comment]
Actually I think I understand.  IntelliJ is OK with having no Project SDK if the module is using a different one.  Our code assumes a valid Project SDK exists.

**Comment by joaoandremartins** [comment]
My suggestion here is to add to the dev_appserver validation an extra check for Project SDK. If it isn't set, then dev_appserver can't be run.

**Comment by patflynn** [comment]
Can we just use the module jdk?

**Comment by joaoandremartins** [comment]
Because there isn't a module - run config relation, and it wouldn't be trivial to implement, I suggest we just error our in this particular scenario. I don't think many users will be hitting this case.

If #926 ever comes to fruition, we would discard the module - run config work too.

**Comment by patflynn** [comment]
There is a deployment source module association.

I'm fine with a solution that tells the user to set a project sdk if it's null.
