### ISSUE TITLE
CDB throwing java.lang.Throwable

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#1290]
From user report:

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:401)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:182)
	at com.google.cloud.tools.intellij.debugger.CloudBreakpointHandler.registerBreakpoint(CloudBreakpointHandler.java:347)
	at com.google.cloud.tools.intellij.debugger.CloudBreakpointHandler.registerBreakpoint(CloudBreakpointHandler.java:74)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.a(XDebugSessionImpl.java:399)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.a(XDebugSessionImpl.java:387)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.b(XDebugSessionImpl.java:529)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:305)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.init(XDebugSessionImpl.java:265)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.a(XDebuggerManagerImpl.java:238)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:181)
	at com.google.cloud.tools.intellij.debugger.CloudDebuggerRunner.createContentDescriptor(CloudDebuggerRunner.java:97)
	at com.google.cloud.tools.intellij.debugger.CloudDebuggerRunner.doExecute(CloudDebuggerRunner.java:82)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:441)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:296)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:441)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:121)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:533)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by patflynn** [comment]
It looks like the cause is setting snapshots in JSPs.
