### ISSUE TITLE
Failed profile picture loads is sometimes causing errors in the IDE

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1377]
this is on 2016.3.2.

my guess is that if `isGoodSize(icon)` is returning false, because the profile picture icon ends up having less than 1px width and/org height when it fails to load.

User error report:
```
Exception class name: java.lang.Throwable
Exception message: javax.swing.ImageIcon@29b7176
Stack trace:
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:135)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:105)
	at com.intellij.openapi.util.IconLoader.getDisabledIcon(IconLoader.java:294)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateIcon(ActionButton.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionButton.presentationPropertyChanded(ActionButton.java:375)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at com.intellij.openapi.actionSystem.Presentation.setIcon(Presentation.java:217)
	at com.google.cloud.tools.intellij.login.ui.GoogleLoginActionButton.updateUi(GoogleLoginActionButton.java:69)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$AndroidUiFacade$2.run(IntellijGoogleLoginService.java:523)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by patflynn** [comment]
This should be an Android Studio bug as well.
