### ISSUE TITLE
User Report: Strange appengine-web.xml error. Appears as though the file is python?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1379]
app.name.version	
IntelliJ IDEA
app.version.major	
2016
app.version.minor	
3.6
java.version	
1.8.0_25
java.vm.vendor	
Oracle Corporation
os.name	
Windows 8
plugin.version	
17.2.3

```
Exception message: appengine-web.xml PSI File Web2Py file with name appengine-web.xml is not an XmlFile. It was chosen from the following appengine-web.xml's that were found: [.../web/WEB-INF/appengine-web.xml,.../out/artifacts/...._war_exploded/WEB-INF/appengine-web.xml]

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineAssetProvider.loadAppEngineStandardWebXml(DefaultAppEngineAssetProvider.java:78)
	at com.google.cloud.tools.intellij.appengine.facet.AppEngineStandardFacet.getAppEngineStandardWebXml(AppEngineStandardFacet.java:97)
	at com.google.cloud.tools.intellij.appengine.facet.AppEngineStandardFacet.isFlexCompatEnvironment(AppEngineStandardFacet.java:64)
	at com.google.cloud.tools.intellij.appengine.facet.AppEngineStandardFacet.isNonStandardCompatEnvironment(AppEngineStandardFacet.java:84)
	at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.lambda$findAppEngineModulesUsingUnsupportedLanguageLevel$1(AppEngineStandardUnsupportedJavaVersionCheck.java:80)
	at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck$$Lambda$1023/949175342.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:879)
	at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.findAppEngineModulesUsingUnsupportedLanguageLevel(AppEngineStandardUnsupportedJavaVersionCheck.java:73)
	at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.runActivity(AppEngineStandardUnsupportedJavaVersionCheck.java:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:146)
	at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$585/391506421.run(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:160)
	at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$586/1089540854.run(Unknown Source)
	at com.intellij.openapi.project.DumbServiceImpl.d(DumbServiceImpl.java:342)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$1004/2107610911.run(Unknown Source)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:321)
	at com.intellij.openapi.project.DumbServiceImpl.c(DumbServiceImpl.java:303)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$1002/1372618572.run(Unknown Source)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
	at com.intellij.openapi.project.DumbServiceImpl.e(DumbServiceImpl.java:302)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$1001/856046298.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:76)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nbashirbello** [comment]
What user action causes this error?

**Comment by patflynn** [comment]
no idea. :)

**Comment by etanshaul** [comment]
not reproducible (and not seen since)
