### ISSUE TITLE
Spring boot app on Java 8 fails to start

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1439]
Steps to reproduce:

1. checkout: https://github.com/halldors/springhelloworld
1. import into Intellij
1. try to run the local dev server

observe:

```
2017-05-10 18:12:57.169:INFO:oejs.Server:main: jetty-9.3.16.v20170120
2017-05-10 18:12:57.507:WARN:oejur.Resource:main: java.net.URISyntaxException: Illegal character in path at index 49: file:/C:/Users/patrick/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.3.16.v20170120-nolog.jar
2017-05-10 18:12:57.508:WARN:oejw.WebAppContext:main: Failed startup of context c.g.a.t.d.j.DevAppEngineWebAppContext@77c2494c{/,file:///C:/Users/patrick/Projects/springhelloworld/build/libs/exploded/springhelloworld.war/,UNAVAILABLE}{C:\Users\patrick\Projects\springhelloworld\build\libs\exploded\springhelloworld.war}
java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in path at index 49: file:/C:/Users/patrick/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.3.16.v20170120-nolog.jar
	at org.eclipse.jetty.util.resource.Resource.getURI(Resource.java:382)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.isFromExcludedJar(AnnotationConfiguration.java:784)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.getNonExcludedInitializers(AnnotationConfiguration.java:877)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:444)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:494)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1361)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:345)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:262)
	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:45)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:217)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:215)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:215)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:349)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:222)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:213)
Caused by: 
java.net.URISyntaxException: Illegal character in path at index 49: file:/C:/Users/patrick/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.3.16.v20170120-nolog.jar
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:939)
	at org.eclipse.jetty.util.resource.Resource.getURI(Resource.java:378)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.isFromExcludedJar(AnnotationConfiguration.java:784)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.getNonExcludedInitializers(AnnotationConfiguration.java:877)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:444)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:494)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1361)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:345)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:262)
	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:45)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:217)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:215)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:215)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:349)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:222)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:213)
2017-05-10 18:12:57.534:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@3d285d7e{HTTP/1.1,[http/1.1]}{localhost:8080}
2017-05-10 18:12:57.535:INFO:oejs.Server:main: Started @3139ms
May 10, 2017 6:12:57 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:8080/
May 10, 2017 6:12:57 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:8080/_ah/admin
May 10, 2017 6:12:57 PM com.google.appengine.tools.development.DevAppServerImpl doStart
INFO: Dev App Server is now running

```

**Comment by chanseokoh** [comment]
java.net.URISyntaxException: Illegal character in path at index 49: file:/C:/Users/patrick/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.3.16.v20170120-nolog.jar

The 50th character (index 49) in the URI is a space (`" "`) in `.../Cloud SDK/...`.

**Comment by ludoch** [comment]
So it might be a bug for the devsapperver. Mind filing an internal bug?

**Comment by patflynn** [comment]
@ludoch

**Comment by ludoch** [comment]
So it is only with a SpringBoot app?

**Comment by patflynn** [comment]
No, this appears to be broken for Java8 in general on Windows.

**Comment by patflynn** [comment]
filed: b/38221393

**Comment by ludoch** [comment]
On it...

**Comment by hugo-ayala** [comment]
Hi guys, what was the outcome of this? I'm getting the same error after following steps on https://cloud.google.com/appengine/docs/standard/java/tools/using-maven

**Comment by patflynn** [comment]
Are you on the latest version of the Cloud SDK?

This bug was related to having spaces in the path so a workaround is to
move the Cloud SDK into a directory that has no whitespaces.  I believe the
latest version of the SDK should not have this problem though.

**Comment by hugo-ayala** [comment]
You are absolutely right!

I had an outdated version of the Cloud SDK...I ran the installer but forgot the important note about running gcloud components update.

**Comment by patflynn** [comment]
@hugo-ayala great to hear. Thanks for the feedback.
