### ISSUE TITLE
Error validation Cloud SDK location

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1447]
I'm guessing this happens because:
1: the SDK directory is pointed at App Engine SDK which also has a VERSION file
2: we are parsing the VERSION file before we check that we're in a valid Cloud SDK location.

```
com.google.cloud.tools.appengine.cloudsdk.CloudSdkVersionFileParseException: Pattern found in the Cloud SDK version file could not be parsed: release: "1.9.52"
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:356)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdkVersion(CloudSdk.java:462)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdk(CloudSdk.java:455)
	at com.google.cloud.tools.intellij.appengine.sdk.DefaultCloudSdkService.validateCloudSdk(DefaultCloudSdkService.java:113)
	at com.google.cloud.tools.intellij.appengine.sdk.CloudSdkService.validateCloudSdk(CloudSdkService.java:71)
	at com.google.cloud.tools.intellij.appengine.sdk.CloudSdkPanel.buildSdkMessage(CloudSdkPanel.java:108)
	at com.google.cloud.tools.intellij.appengine.sdk.CloudSdkPanel.checkSdk(CloudSdkPanel.java:87)
	at com.google.cloud.tools.intellij.appengine.sdk.CloudSdkPanel$CloudSdkCheckerRunnable.run(CloudSdkPanel.java:246)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Pattern "release: "1.9.52"" is not a valid CloudSdkVersion.
	at com.google.cloud.tools.appengine.cloudsdk.serialization.CloudSdkVersion.<init>(CloudSdkVersion.java:56)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:352)
```

**Comment by etanshaul** [comment]
I'm a little perplexed by this one.

In every location where we accept a cloud sdk we also check that its a valid location..so I wasn't able to trigger this error.

I even tested out starting with a valid cloud sdk directory, then swapping out its contents (outside of the IDE) with the appengine-sdk to see if this impostor sdk would trigger the error. And it does not - we get a nice error in the IDE saying that the SDK is misconfigured.

**Comment by patflynn** [comment]
close it as not-reproducible. We can re-open if it ever pops up again.

**Comment by etanshaul** [comment]
sure.

I just tried manually changing the version file in the real cloud SDK to the version in this error (1.9.52) and still can't trigger the error.

Closing as not-reproducible.
