### ISSUE TITLE
2017.2 EAP Darcula exception

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1450]
Exception class name: java.lang.NoSuchMethodError: com.intellij.ide.ui.laf.darcula.DarculaUIUtil.paintFocusRing(Ljava/awt/Graphics;IIII)V
Exception message: com.intellij.ide.ui.laf.darcula.DarculaUIUtil.paintFocusRing(Ljava/awt/Graphics;IIII)V
Stack trace:
java.lang.NoSuchMethodError: com.intellij.ide.ui.laf.darcula.DarculaUIUtil.paintFocusRing(Ljava/awt/Graphics;IIII)V
	at com.google.cloud.tools.intellij.ui.CustomizableComboBox.paint(CustomizableComboBox.java:222)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)

**Comment by etanshaul** [comment]
closing as user was on plugin version 16.11.6
