### ISSUE TITLE
Flaky Tests due to a detected Project 'leak'

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1459]
Our CI builds are frequently red due to this issue:
```

com.google.cloud.tools.intellij.debugger.CloudExecutionStackTest > testGetTopFrame_nullFramesReturnsNull SKIPPED

com.google.cloud.tools.intellij.debugger.CloudExecutionStackTest > testGetTopFrame_nonNull SKIPPED

com.google.cloud.tools.intellij.debugger.ui.CloudAttachDialogTest > testDebuggableModuleSelected FAILED
    junit.framework.AssertionFailedError: Too many projects leaked: 
    Project (Disposed) testDockerfileStartsDisabledAndWithModuleSettingcom.google.cloud.tools.intellij.appengine.cloud.flexible.AppEngineFlexibleDeploymentEditorTest.testDockerfileStartsDisabledAndWithModuleSetting
    Project (Disposed) testSuggestion_nullPathcom.google.cloud.tools.intellij.appengine.cloud.flexible.SelectConfigDestinationFolderDialogTest.testSuggestion_nullPath
    Project (Disposed) testRemoveConsolePanecom.google.cloud.tools.intellij.debugger.CloudDebugProcessTest.testRemoveConsolePane
    Project (Disposed) testSuggestioncom.google.cloud.tools.intellij.appengine.cloud.flexible.SelectConfigDestinationFolderDialogTest.testSuggestion
    Project (Disposed) testSuggestion_noParentcom.google.cloud.tools.intellij.appengine.cloud.flexible.SelectConfigDestinationFolderDialogTest.testSuggestion_noParent

    Please see '/Volumes/BuildData/tmpfs/tmp/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2017.1/7f417b38c7a1613648ac9d9b266a2fb936d60407/ideaIU-2017.1/leakedProjects.hprof.zip' for a memory dump
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.TestCase.fail(TestCase.java:227)
        at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:293)
        at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:254)
        at com.intellij.testFramework.PlatformTestCase.doCreateProject(PlatformTestCase.java:249)
        at com.intellij.testFramework.PlatformTestCase.setUpProject(PlatformTestCase.java:234)
        at com.intellij.testFramework.PlatformTestCase.setUp(PlatformTestCase.java:202)
        at com.google.cloud.tools.intellij.debugger.ui.CloudAttachDialogTest.setUp(CloudAttachDialogTest.java:62)

357 tests completed, 1 failed, 2 skipped
:google-cloud-tools-plugin:test FAILED

```

**Comment by etanshaul** [comment]
Thanks, good to have an issue for this. I'm still investigating a fix.
