### ISSUE TITLE
crash during app.yaml parsing

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1554]
while parsing a block collection
 in 'reader', line 5, column 3:
      - url: /
      ^
expected <block end>, but found Key
 in 'reader', line 6, column 3:
      script:
      ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:513)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:152)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:448)
	at com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineProjectService.getValueFromAppYaml(DefaultAppEngineProjectService.java:287)
	at com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineProjectService.getFlexibleRuntimeFromAppYaml(DefaultAppEngineProjectService.java:262)
	at com.google.cloud.tools.intellij.appengine.cloud.CloudSdkAppEngineHelper.createDeployRunner(CloudSdkAppEngineHelper.java:170)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineRuntimeInstance.deploy(AppEngineRuntimeInstance.java:71)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl$2.connected(ServerConnectionImpl.java:148)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.connectIfNeeded(ServerConnectionImpl.java:355)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.deploy(ServerConnectionImpl.java:128)
	at com.intellij.remoteServer.impl.runtime.DeployToServerState.execute(DeployToServerState.java:69)
	at com.intellij.execution.runners.DefaultProgramRunnerKt.executeState(DefaultProgramRunner.kt:39)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.kt:29)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.RunProfileStarter.executeAsync(RunProfileStarter.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$7(ExecutionManagerImpl.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$8(ExecutionManagerImpl.java:447)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:304)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:447)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:37)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfigurationAsync(ProgramRunnerUtil.java:125)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:58)
	at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:69)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:539)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nkibler** [comment]
Can you post your `app.yaml` contents?

**Comment by patflynn** [comment]
nope. :). this is another user reported (see the pink crash label as an indication)

**Comment by etanshaul** [comment]
I'm unable to reproduce this. Everything I've tried to generate a yaml parsing error results in the exception being properly caught with a human readable message to the user.

Will close for now and keep an eye out for other reports.
