### ISSUE TITLE
crash on 2017.1.5

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1555]
java.lang.RuntimeException: No environment.
	at com.google.cloud.tools.intellij.appengine.cloud.MavenBuildDeploymentSource.lambda$getFile$0(MavenBuildDeploymentSource.java:133)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.google.cloud.tools.intellij.appengine.cloud.MavenBuildDeploymentSource.getFile(MavenBuildDeploymentSource.java:132)
	at com.google.cloud.tools.intellij.appengine.cloud.CloudSdkAppEngineHelper.createDeployRunner(CloudSdkAppEngineHelper.java:125)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineRuntimeInstance.deploy(AppEngineRuntimeInstance.java:71)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl$2.connected(ServerConnectionImpl.java:148)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl$6.connected(ServerConnectionImpl.java:365)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineCloudType$AppEngineServerConnector.connect(AppEngineCloudType.java:138)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.connectIfNeeded(ServerConnectionImpl.java:360)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.deploy(ServerConnectionImpl.java:128)
	at com.intellij.remoteServer.impl.runtime.DeployToServerState.execute(DeployToServerState.java:69)
	at com.intellij.execution.runners.DefaultProgramRunnerKt.executeState(DefaultProgramRunner.kt:39)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.kt:29)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.RunProfileStarter.executeAsync(RunProfileStarter.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nkibler** [comment]
How is your project configured? It looks like this could happen if the project doesn't have the standard or flex App Engine facets, but it has a `MavenBuildDeploymentSource`. I'm not sure when `.getFile()` is called, but is this on a newly created/imported project? Or did it already exist and you potentially removed the App Engine facet from the project?

**Comment by patflynn** [comment]
this is a user reported bug.  you can get more context from our crash reporting tool. Check with @etanshaul for the details and FYI I've added you to the users with access.
