### ISSUE TITLE
User Crash:  ISE "Version Control" window isn't registered

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1643]
IntelliJ IDEA  2017.2.3
 1.8.0_152-release
 Windows 7
 17.8.2
Stacktrace:
```
java.lang.IllegalStateException: window with id="Version Control" isn't registered
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.checkId(ToolWindowManagerImpl.java:772)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.isToolWindowVisible(ToolWindowManagerImpl.java:1669)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.isVisible(ToolWindowImpl.java:264)
	at com.intellij.vcs.log.impl.VcsLogTabsWatcher.getSelectedTabName(VcsLogTabsWatcher.java:65)
	at com.intellij.vcs.log.impl.VcsLogTabsWatcher.access$100(VcsLogTabsWatcher.java:41)
	at com.intellij.vcs.log.impl.VcsLogTabsWatcher$MyRefreshPostponedEventsListener.selectionChanged(VcsLogTabsWatcher.java:134)
	at com.intellij.vcs.log.impl.VcsLogTabsWatcher$MyRefreshPostponedEventsListener.stateChanged(VcsLogTabsWatcher.java:173)
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy81.stateChanged(Unknown Source)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.fireStateChanged(ToolWindowManagerImpl.java:1653)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:568)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.unregisterToolWindow(ToolWindowManagerImpl.java:1233)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.lambda$registerDisposable$9(ToolWindowManagerImpl.java:1208)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:151)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:151)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:137)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:121)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$12(ProjectManagerImpl.java:680)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1030)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:674)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:698)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:91)
	at com.intellij.ide.impl.NewProjectUtil.closePreviousProject(NewProjectUtil.java:218)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:145)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
	at com.intellij.ide.actions.ImportModuleAction.doCreateFromWizard(ImportModuleAction.java:95)
	at com.intellij.ide.actions.ImportModuleAction.lambda$createFromWizard$0(ImportModuleAction.java:89)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.ide.actions.ImportModuleAction.createFromWizard(ImportModuleAction.java:89)
	at com.intellij.openapi.vcs.checkout.NewProjectCheckoutListener.processCheckedOutDirectory(NewProjectCheckoutListener.java:50)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.notifyCheckoutListeners(CompositeCheckoutListener.java:61)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.directoryCheckedOut(CompositeCheckoutListener.java:52)
	at com.google.cloud.tools.intellij.vcs.GcpCheckoutProvider$1.onSuccess(GcpCheckoutProvider.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:462)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.lambda$run$0(ProgressManagerImpl.java:189)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nkibler** [comment]
This isn't reproducible and seems like a transient bug, closing for now.
