### ISSUE TITLE
devappserver not there but can't add it.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1683]
<img width="988" alt="screen shot 2017-10-05 at 4 09 58 pm" src="https://user-images.githubusercontent.com/7862557/31256497-c8b8ae82-a9e7-11e7-9db5-4643d889d7f6.png">

in demo so can't provide more details atm

**Comment by patflynn** [comment]
`017-10-05 16:11:57,219 [ 854134]  ERROR - tions.ex.ConfigurableCardPanel - cannot reset configurable 
com.intellij.openapi.util.TraceableDisposable$DisposalException: 'Google App Engine Standard Local Server' already disposed:
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:94)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.c(LibraryImpl.java:160)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.getFiles(LibraryImpl.java:186)
	at com.intellij.openapi.roots.ui.configuration.libraryEditor.ExistingLibraryEditor.getFiles(ExistingLibraryEditor.java:134)
	at com.intellij.openapi.roots.ui.configuration.libraryEditor.LibraryRootsComponent.updatePropertiesLabel(LibraryRootsComponent.java:139)
	at com.intellij.openapi.roots.ui.configuration.libraryEditor.LibraryRootsComponent.<init>(LibraryRootsComponent.java:115)
	at com.intellij.openapi.roots.ui.configuration.libraryEditor.LibraryRootsComponent.<init>(LibraryRootsComponent.java:95)
	at com.intellij.j2ee.appServerIntegrations.ApplicationServerConfigurable.<init>(ApplicationServerConfigurable.java:78)
	at com.intellij.j2ee.appServerIntegrations.impl.ApplicationServerImpl.createConfigurable(ApplicationServerImpl.java:59)
	at com.intellij.j2ee.appServerIntegrations.AppServerDKsEditor.refreshList(AppServerDKsEditor.java:163)
	at com.intellij.j2ee.appServerIntegrations.AppServerDKsEditor.reset(AppServerDKsEditor.java:127)
	at com.intellij.j2ee.appServerIntegrations.ApplicationServersConfigurable.reset(ApplicationServersConfigurable.java:62)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.reset(ConfigurableWrapper.java:174)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.reset(ConfigurableCardPanel.java:127)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$3.actionPerformed(ConfigurableEditor.java:83)
	at com.intellij.ui.components.labels.SwingActionLink.linkSelected(SwingActionLink.java:41)
	at com.intellij.ui.components.labels.SwingActionLink.linkSelected(SwingActionLink.java:28)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:156)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:364)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:341)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:735)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:77)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2017-10-05 16:11:57,220 [ 854135]  ERROR - tions.ex.ConfigurableCardPanel - IntelliJ IDEA 2017.1.3  Build #IU-171.4424.56 
2017-10-05 16:11:57,220 [ 854135]  ERROR - tions.ex.ConfigurableCardPanel - JDK: 1.8.0_112-release 
2017-10-05 16:11:57,220 [ 854135]  ERROR - tions.ex.ConfigurableCardPanel - VM: OpenJDK 64-Bit Server VM 
2017-10-05 16:11:57,220 [ 854135]  ERROR - tions.ex.ConfigurableCardPanel - Vendor: JetBrains s.r.o 
2017-10-05 16:11:57,220 [ 854135]  ERROR - tions.ex.ConfigurableCardPanel - OS: Mac OS X 
`

**Comment by patflynn** [comment]
another odd thing is that no error report dialogue shows up

**Comment by patflynn** [comment]
this is actually happening when I try to install jetty too so maybe not us.

**Comment by patflynn** [comment]
upgrading to 2017.2 fixes this.
