### ISSUE TITLE
2017.3 throws duplicate inspection registration errors

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1854]
In IJ 2017.3 it seems that the code inspections are loaded earlier than previously (at IDE load rather than project load).

When doing a clean load of the IDE with our plugin and the bundled legacy App Engine Integration plugin, we get exceptions due to duplicate `AppEngineForbiddenCodeInspection` registration on the IDEA welcome screen (prior to loading a project and prior to following our prompt to disable the legacy plugin):

```
Short name 'AppEngineForbiddenCode' is not unique
class 'com.google.cloud.tools.intellij.appengine.inspections.AppEngineForbiddenCodeInspection' in PluginDescriptor[name='Google Cloud Tools', classpath='/usr/local/google/home/eshaul/dev/google-cloud-intellij/google-cloud-tools-plugin/build/idea-sandbox/plugins/google-cloud-tools']
and
class'com.intellij.appengine.inspections.AppEngineForbiddenCodeInspection' in PluginDescriptor[name='Google App Engine Integration', classpath='/usr/local/google/home/eshaul/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2017.3.3/d9c0de3b98d427c172b416ab96e646657af945bb/ideaIU-2017.3.3/plugins/GoogleAppEngine']
conflict [Plugin: com.google.gct.core]
com.intellij.diagnostic.PluginException: Short name 'AppEngineForbiddenCode' is not unique
class 'com.google.cloud.tools.intellij.appengine.inspections.AppEngineForbiddenCodeInspection' in PluginDescriptor[name='Google Cloud Tools', classpath='/usr/local/google/home/eshaul/dev/google-cloud-intellij/google-cloud-tools-plugin/build/idea-sandbox/plugins/google-cloud-tools']
and
class'com.intellij.appengine.inspections.AppEngineForbiddenCodeInspection' in PluginDescriptor[name='Google App Engine Integration', classpath='/usr/local/google/home/eshaul/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2017.3.3/d9c0de3b98d427c172b416ab96e646657af945bb/ideaIU-2017.3.3/plugins/GoogleAppEngine']
conflict [Plugin: com.google.gct.core]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
```

**Comment by etanshaul** [comment]
tested on 2017.2 and 2018.1 (EAP) and is NOT an issue. Seems to only affect 2017.3

**Comment by etanshaul** [comment]
Even more specifically, I can only reproduce this in **2017.3.3**

Here is what happens:
![image](https://user-images.githubusercontent.com/1735744/35519476-5b514e8e-04e2-11e8-8b25-0deb97695105.png)

**Comment by ivanporty** [comment]
I checked IDEA's decompiled App Engine plugin for 2017.2/2017.3.3 and it seems they have the same inspection short name, so it must be something within inspection bootstrapping code. I guess we have to change the short name and I'll check the bootstrapping code as well.

**Comment by etanshaul** [comment]
yeah. the duplicated short name has been around forever.
