### ISSUE TITLE
Project selector logged out view still shows cloud project and user name

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1876]
1) Sign in to your account
2) verify that the selector shows the project, avatar, and email
3) sign out
4) look at the project selector widget:

![image](https://user-images.githubusercontent.com/1735744/35642498-4c1afb30-0691-11e8-9be4-5555766e332e.png)

It should show the signed out message. Instead it still shows the last signed in email and project name (and the avatar is now the generic one).

**Comment by etanshaul** [comment]
There is actually a more serious side effect of this:

1) perfrom steps 1-3 above
2) open the cloud library selector
3) notice that you are logged out but the default project is still show. also notice that the enable api checkbox is enabled and checked. This should be disabled when not signed in.

<img width="830" alt="screen shot 2018-01-31 at 3 48 16 pm" src="https://user-images.githubusercontent.com/1735744/35646748-2debd0f0-069e-11e8-9fc5-1a63f904fde5.png">

Proceeding to add the library and enable the API results in an exception:

```
Cannot enable APIs: logged in user not found.
java.lang.Throwable: Cannot enable APIs: logged in user not found.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.google.cloud.tools.intellij.apis.CloudApiManager.enableApis(CloudApiManager.java:77)
	at com.google.cloud.tools.intellij.apis.AddCloudLibrariesDialog.lambda$doOKAction$2(AddCloudLibrariesDialog.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:575)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by etanshaul** [comment]
the takeaway is that when the user is not signed in, it should not behave as though a project is selected. If we want to display the project to the user like we discussed, that is fine, but it should not behave as though one is actually selected.

**Comment by ivanporty** [comment]
Yes, so we need to decide what project selector does - does it keep selected project or does it keep selected project and Google account logged in status. I mean, once you selected project (being signed in), and then you signed out, does it turn all selections to invalid? What do you think about choices:
* make client code check for `isLoggedIn()` as a `LoginService` function
* make ProjectSelector fire event with `selected cloud project == null` meaning no one signed in? 

I think what we have now is a bit cleaner - project selector only selects projects.
Oh, and we probably need to not set active project if no one is logged in to prevent cases like this.

**Comment by etanshaul** [comment]
> Oh, and we probably need to not preset active project if no one is logged in to prevent cases like this.

We definitely need to do this. Doesn't doing this fix the entire issue I described?

**Comment by ivanporty** [comment]
Yes, this will do it.
I mean, for some other cases (not in the modal dialog, or maybe in parallel, in browser window), a user can log out with project already selected and project selector won't be able to do a lot about it. In this case I thought it could be a good practice to also check for logged in status before final action.

**Comment by etanshaul** [comment]
If we leave it up to the client to check the logged in status, doesn't that still leave the need to update the project selector UI when logging out (for non-modal dialogs)? in that case I'd expect the UI to update don't you think?

**Comment by ivanporty** [comment]
Sure, project selector will update itself to show prompt to sign in in this case - that's what we plan to do in (PR #1879), is that what you mean?

**Comment by etanshaul** [comment]
Ah yea sorry. I was crossing two different things (updating the UI when logging out vs having the the cloud project actually being cleared). I think you are right that its good practice to check for login status.
