### ISSUE TITLE
MavenProjectsManager NPE user submitted

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1928]
org/jetbrains/idea/maven/project/MavenProjectsManager
Stack trace:
java.lang.NoClassDefFoundError: org/jetbrains/idea/maven/project/MavenProjectsManager
	at com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineProjectService.isMavenModule(DefaultAppEngineProjectService.java:159)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardFacetEditor.isManagedLibrariesEnabled(AppEngineStandardFacetEditor.java:158)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardFacetEditor.createUIComponents(AppEngineStandardFacetEditor.java:149)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardFacetEditor.$$$setupUI$$$(AppEngineStandardFacetEditor.java)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardFacetEditor.<init>(AppEngineStandardFacetEditor.java:57)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardFacetConfiguration.createEditorTabs(AppEngineStandardFacetConfiguration.java:46)
	at com.intellij.facet.impl.ui.FacetEditorImpl.<init>(FacetEditorImpl.java:59)
	at com.intellij.facet.impl.ProjectFacetsConfigurator.getOrCreateEditor(ProjectFacetsConfigurator.java:189)
	at com.intellij.facet.impl.ui.facetType.FacetTypeEditor.a(FacetTypeEditor.java:86)
	at com.intellij.facet.impl.ui.facetType.FacetTypeEditor.createComponent(FacetTypeEditor.java:101)

**Comment by etanshaul** [comment]
closing for same reason as #1939
