### ISSUE TITLE
User reported error with project selector

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1934]
plugin version: 18.2.1
IJ version: 2017.3.4

```
Argument for @NotNull parameter 'message' of com/intellij/openapi/ui/ValidationInfo.<init> must not be null
Stack trace:
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'message' of com/intellij/openapi/ui/ValidationInfo.<init> must not be null
	at com.intellij.openapi.ui.ValidationInfo.$$$reportNull$$$0(ValidationInfo.java)
	at com.intellij.openapi.ui.ValidationInfo.<init>(ValidationInfo.java)
	at com.google.cloud.tools.intellij.project.ProjectSelectionDialog$1.lambda$onFailure$1(ProjectSelectionDialog.java:214)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
```

**Comment by etanshaul** [comment]
@ivanporty mind checking to see if there's anything for us to do here?

**Comment by ivanporty** [comment]
Sure.
