### ISSUE TITLE
User reported NPE in AppEngineStandardUltimateWebIntegration

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1981]
Description
null
Stack trace:
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.appengine.facet.impl.AppEngineStandardUltimateWebIntegration.suggestParentDirectoryForAppEngineWebXml(AppEngineStandardUltimateWebIntegration.java:100)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardSupportProvider.addSupport(AppEngineStandardSupportProvider.java:144)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardSupportProvider.access$300(AppEngineStandardSupportProvider.java:75)
	at com.google.cloud.tools.intellij.appengine.facet.standard.AppEngineStandardSupportProvider$AppEngineSupportConfigurable.addSupport(AppEngineStandardSupportProvider.java:300)
	at com.google.cloud.tools.intellij.appengine.facet.AddAppEngineFrameworkSupportDialog$1.run(AddAppEngineFrameworkSupportDialog.java:70)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:38)

**Comment by etanshaul** [comment]
@ivanporty I'm dividing these out. Mind taking a look?
