### ISSUE TITLE
User reported NPE in CloudLibraryProjectState

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#2175]
IDEA: 2017.2

java.lang.NullPointerException
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.lambda$getModuleDependencies$1(CloudLibraryProjectState.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:954)
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.getModuleDependencies(CloudLibraryProjectState.java:131)
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.loadManagedLibraries(CloudLibraryProjectState.java:104)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.syncManagedProjectLibraries(CloudLibraryProjectState.java:94)
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState$1.projectsScheduled(CloudLibraryProjectState.java:76)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.fireProjectScheduled(MavenProjectsManager.java:1259)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.access$1200(MavenProjectsManager.java:81)
	at org.jetbrains.idea.maven.project.MavenProjectsManager$5.projectsUpdated(MavenProjectsManager.java:456)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.fireProjectsUpdated(MavenProjectsTree.java:1480)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.access$400(MavenProjectsTree.java:59)
	at org.jetbrains.idea.maven.project.MavenProjectsTree$UpdateContext.fireUpdatedIfNecessary(MavenProjectsTree.java:1537)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.update(MavenProjectsTree.java:478)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.update(MavenProjectsTree.java:442)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessorReadingTask.perform(MavenProjectsProcessorReadingTask.java:64)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.doProcessPendingTasks(MavenProjectsProcessor.java:132)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.access$000(MavenProjectsProcessor.java:32)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor$2.run(MavenProjectsProcessor.java:107)
	at org.jetbrains.idea.maven.utils.MavenUtil.lambda$runInBackground$5(MavenUtil.java:460)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ivanporty** [comment]
I agree, we definitely saw plugin versions before. We probably need to double check this. I briefly looked into the source and couldn't see how this error could happen with the current source code too. Shall we close this as already fixed then, @etanshaul?
