### ISSUE TITLE
User reported FileNotFoundException

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2191]
Plugin version 18.6.1
IDEA 2018.1

```
com.google.cloud.tools.appengine.api.AppEngineException: java.nio.file.NoSuchFileException: /***/appengine-web.xml
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.isJava8(CloudSdkAppEngineDevServer1.java:224)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.run(CloudSdkAppEngineDevServer1.java:113)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:79)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartupPolicy.java:161)
	at com.intellij.javaee.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:76)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /***/appengine-web.xml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.isJava8(CloudSdkAppEngineDevServer1.java:217)
```

**Comment by patflynn** [comment]
we should probably take a look at impact before the next milestone release.

**Comment by etanshaul** [comment]
yeah I noticed too. was planning on looking into it today.
