### ISSUE TITLE
User reported jdom Element NoSuchMethodError

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2255]
IDEA 2017.3.4
plugin 18.8.1
```
Description
org.jdom.Element.detach()Lorg/jdom/Element;
Stack trace:
java.lang.NoSuchMethodError: org.jdom.Element.detach()Lorg/jdom/Element;
	at com.google.cloud.tools.intellij.appengine.java.migration.AppEngineStandardFacetMigrationConversionProcessor.process(AppEngineStandardFacetMigrationConversionProcessor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.migration.AppEngineStandardFacetMigrationConversionProcessor.process(AppEngineStandardFacetMigrationConversionProcessor.java:28)
	at com.intellij.conversion.impl.ConversionRunner.process(ConversionRunner.java:171)
	at com.intellij.conversion.impl.ui.ConvertProjectDialog.doOKAction(ConvertProjectDialog.java:129)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1877)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1838)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6541)
```

**Comment by etanshaul** [comment]
We are getting a bunch of these. I'm gonna try and figure out whats going on here for the next release.
