### ISSUE TITLE
User reported error: only one facet allowed

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2292]
```
Only one 'Google App Engine Flexible' facet per module allowed, but 2 facets found in module
Stack trace:
java.lang.Throwable: Only one 'Google App Engine Flexible' facet per module allowed, but 2 facets found in module
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.facet.FacetManagerImpl.commit(FacetManagerImpl.java:469)
	at com.intellij.facet.FacetManagerImpl.commit(FacetManagerImpl.java:381)
	at com.intellij.facet.impl.FacetModelImpl.commit(FacetModelImpl.java:96)
	at com.intellij.facet.FacetManagerImpl.addFacet(FacetManagerImpl.java:146)
	at com.google.cloud.tools.intellij.appengine.java.facet.flexible.AppEngineFlexibleSupportProvider$AppEngineFlexibleSupportConfigurable.addSupport(AppEngineFlexibleSupportProvider.java:188)
	at com.google.cloud.tools.intellij.appengine.java.facet.AddAppEngineFrameworkSupportDialog$1.run(AddAppEngineFrameworkSupportDialog.java:70)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:37)
	at com.google.cloud.tools.intellij.appengine.java.facet.AddAppEngineFrameworkSupportDialog.doOKAction(AddAppEngineFrameworkSupportDialog.java:73)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1868)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1828)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
```

plugin 18.10.1
idea 2018.1.6

**Comment by etanshaul** [comment]
@ivanporty can you ptal? I'm dividing up the user reported bugs so we can take a look
