### ISSUE TITLE
Release 18.11.1 error with IDEA 2017.1

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2296]
```
Plugin 'com.google.gct.core' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.AbstractMethodError
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
```

**Comment by etanshaul** [comment]
note: plugin confirmed working in 2017.2 & 2017.3.

**Comment by etanshaul** [comment]
outdated
