### ISSUE TITLE
User reported NPE in addLibrariesToMavenModule

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2320]
```
java.lang.NullPointerException at CloudLibraryDependencyWriter.addLibrariesToMavenModule : __NONE___
Stack trace:
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryDependencyWriter.addLibrariesToMavenModule(CloudLibraryDependencyWriter.java:105)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryDependencyWriter.addLibraries(CloudLibraryDependencyWriter.java:84)
	at com.google.cloud.tools.intellij.cloudapis.maven.MavenCloudApiUiExtension.onCloudLibrariesAddition(MavenCloudApiUiExtension.java:153)
	at com.google.cloud.tools.intellij.cloudapis.DefaultCloudApiUiPresenter.lambda$notifyCloudLibrariesAddition$4(DefaultCloudApiUiPresenter.java:121)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.google.cloud.tools.intellij.cloudapis.DefaultCloudApiUiPresenter.notifyCloudLibrariesAddition(DefaultCloudApiUiPresenter.java:121)
	at com.google.cloud.tools.intellij.cloudapis.AddCloudLibrariesAction.actionPerformed(AddCloudLibrariesAction.java:58)
```

plugin version 18.12.1
intellij version 2018.2.5

**Comment by etanshaul** [comment]
@ivanporty if you have any bandwidth to look at this one as well. Bogged down in docs at the moment.
