### ISSUE TITLE
User reported ClassCastException

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2322]
```
java.lang.ClassCastException at AppEngineDeprecatedRuntimeInspection.isAppEngineWebXmlDeprecatedRuntimeTag : com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
Stack trace:
java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
	at com.google.cloud.tools.intellij.appengine.java.inspections.AppEngineDeprecatedRuntimeInspection.isAppEngineWebXmlDeprecatedRuntimeTag(AppEngineDeprecatedRuntimeInspection.java:107)
	at com.google.cloud.tools.intellij.appengine.java.inspections.AppEngineDeprecatedRuntimeInspection.access$000(AppEngineDeprecatedRuntimeInspection.java:42)
	at com.google.cloud.tools.intellij.appengine.java.inspections.AppEngineDeprecatedRuntimeInspection$1.visitXmlTag(AppEngineDeprecatedRuntimeInspection.java:71)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1040)
	at com.intellij.lang.javascript.psi.e4x.impl.JSXmlLiteralExpressionImpl.accept(JSXmlLiteralExpressionImpl.java:41)
	at com.intellij.codeInspection.InspectionEngine.
```

plugin version 19.1.1

**Comment by ivanporty** [comment]
This happens when React JSX editing support is used in IntelliJ Ultimate edition, which analyzes the Javascript file as a combination of Javascript and XML file.

Please use release 19.1.2 to make sure you will not get this error in the project using Cloud Tools plugin and React JSX files.

**Comment by etanshaul** [comment]
Release 19.1.2 was published with this fix. Thanks for finding the root cause @ivanporty
