### ISSUE TITLE
Release process should check the plugin across all supported IDE version range.

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#2442]
Latest release introduced some incompatible changes but the range remained same (including 2017.2+) which caused this user reported error:

```
Description
com.intellij.openapi.command.WriteCommandAction.writeCommandAction(Lcom/intellij/openapi/project/Project;[Lcom/intellij/psi/PsiFile;)Lcom/intellij/openapi/command/WriteCommandAction$Builder;
Stack trace:
java.lang.NoSuchMethodError: com.intellij.openapi.command.WriteCommandAction.writeCommandAction(Lcom/intellij/openapi/project/Project;[Lcom/intellij/psi/PsiFile;)Lcom/intellij/openapi/command/WriteCommandAction$Builder;
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryDependencyWriter.addLibrariesToMavenModule(CloudLibraryDependencyWriter.java:122)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryDependencyWriter.addLibraries(CloudLibraryDependencyWriter.java:86)
	at com.google.cloud.tools.intellij.cloudapis.maven.MavenCloudApiUiExtension.onCloudLibrariesAddition(MavenCloudApiUiExtension.java:153)
	at com.google.cloud.tools.intellij.cloudapis.DefaultCloudApiUiPresenter.lambda$notifyCloudLibrariesAddition$4(DefaultCloudApiUiPresenter.java:121)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.google.cloud.tools.intellij.cloudapis.DefaultCloudApiUiPresenter.notifyCloudLibrariesAddition(DefaultCloudApiUiPresenter.java:121)
	at com.google.cloud.tools.intellij.cloudapis.AddCloudLibrariesAction.actionPerformed(AddCloudLibrariesAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)


app.name.version
 IntelliJ IDEA
app.version.major
 2017
app.version.minor
 2.2
plugin.version
 19.2.1
```

We need to add a release step to build/sanity check the plugin across all supported ranges if it spans more than current CI range (previous version, current latest, and upcoming EAP).

**Comment by etanshaul** [comment]
agreed. the range will soon be bumped to 2018.2+ so this will make it easier for now.
