### ISSUE TITLE
User reported: NPE in DefaultCloudSdkVersionNotifier.showNotification

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#2481]
```
java.lang.NullPointerException at NotificationsManagerImpl.findWindowForBalloon : __NONE___
Stack trace:
java.lang.NullPointerException
	at com.intellij.notification.impl.NotificationsManagerImpl.findWindowForBalloon(NotificationsManagerImpl.java:310)
	at com.intellij.notification.impl.NotificationsManagerImpl.notifyByBalloon(NotificationsManagerImpl.java:238)
	at com.intellij.notification.impl.NotificationsManagerImpl.showNotification(NotificationsManagerImpl.java:174)
	at com.intellij.notification.impl.NotificationsManagerImpl.lambda$doNotify$1(NotificationsManagerImpl.java:137)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3075)
	at com.intellij.notification.impl.NotificationsManagerImpl.doNotify(NotificationsManagerImpl.java:139)
	at com.intellij.notification.impl.NotificationsManagerImpl.access$700(NotificationsManagerImpl.java:79)
	at com.intellij.notification.impl.NotificationsManagerImpl$MyNotificationListener.notify(NotificationsManagerImpl.java:1075)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy130.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:81)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:70)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3075)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:70)
	at com.intellij.notification.Notification.notify(Notification.java:325)
	at com.google.cloud.tools.intellij.appengine.java.sdk.DefaultCloudSdkVersionNotifier.showNotification(DefaultCloudSdkVersionNotifier.java:79)
	at com.google.cloud.tools.intellij.appengine.java.sdk.DefaultCloudSdkVersionNotifier.notifyIfVersionOutOfDate(DefaultCloudSdkVersionNotifier.java:42)
	at com.google.cloud.tools.intellij.appengine.java.startup.CloudSdkVersionStartupCheck.runActivity(CloudSdkVersionStartupCheck.java:33)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$logActivityDuration$2(StartupManagerImpl.java:152)
	at com.intellij.util.TimeoutUtil.measureExecutionTime(TimeoutUtil.java:74)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:152)
```

IDEA 2019.1
plugin version 19.3.1

**Comment by etanshaul** [comment]
@ivanporty do you have a moment to check this? should just need to check that the cloudsdk update notification happens properly in 2019.1

**Comment by ivanporty** [comment]
From what is seems this looks like an internal IDE issue, we call perfectly correct version of `showNotification`, all non-nullable parameters are set. I think this happened somewhere during the window opening and it was not able to find a window to put a notification on.

**Comment by etanshaul** [comment]
so you weren't able to reproduce? Shall we file a Youtrack issue?

**Comment by ivanporty** [comment]
It might be the rare issue of not using `StartupActivity` properly that started to show up in the new version. I'm not sure you can show notifications from it. Let me check.
