### ISSUE TITLE
User reports exception thrown by Login code in IDEA 15.0.1

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#334]
Exception class name: java.lang.Throwable
Exception message: javax.swing.ImageIcon@1c7fea6
Stack trace:
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:118)
    at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:92)
    at com.intellij.openapi.util.IconLoader.getDisabledIcon(IconLoader.java:285)
    at com.intellij.openapi.actionSystem.impl.ActionButton.updateIcon(ActionButton.java:229)
    at com.intellij.openapi.actionSystem.impl.ActionButton$ActionButtonSynchronizer.propertyChange(ActionButton.java:347)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at com.intellij.openapi.actionSystem.Presentation.setIcon(Presentation.java:217)
    at com.google.gct.login.ui.GoogleLoginActionButton.updateUi(GoogleLoginActionButton.java:62)
    at com.google.gct.login.GoogleLogin$AndroidUiFacade$1.run(GoogleLogin.java:654)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by elharo** [comment]
The Throwable exists only so the error logs can inlcude the stack trace. It's not the real problem. The relevant code is here:

  public static Icon getDisabledIcon(Icon icon) {
    if (icon instanceof LazyIcon) icon = ((LazyIcon)icon).getOrComputeIcon();
    if (icon == null) return null;

    Icon disabledIcon = ourIcon2DisabledIcon.get(icon);
    if (disabledIcon == null) {
      if (!isGoodSize(icon)) {
        LOG.error(icon); // # 22481
        return EMPTY_ICON;
      }


  public static boolean isGoodSize(@NotNull final Icon icon) {
    return icon.getIconWidth() > 0 && icon.getIconHeight() > 0;
  }


it appears we're using an icon that is zero width, height, or both.

**Comment by elharo** [comment]
I'm guessing that the height and width are getting reported as -1 because the image the icon depends on hasn't loaded yet. If so, this is unlikely to be a routine error.

**Comment by etanshaul** [comment]
obsolete (has been fixed + this is referring to a very outdated version of IJ)
