### ISSUE TITLE
CDB related error reported by user on 2016.2 EAP

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#705]
User submitted error report

Exception class name: java.lang.NoSuchMethodError: com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.getAllChildren()Ljava/util/List;
Exception message: com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.getAllChildren()Ljava/util/List;
Stack trace:
java.lang.NoSuchMethodError: com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.getAllChildren()Ljava/util/List;
	at com.google.cloud.tools.intellij.debugger.ui.BreakpointConfigurationPanel.saveTo(BreakpointConfigurationPanel.java:232)
	at com.google.cloud.tools.intellij.debugger.ui.BreakpointConfigurationPanel.saveTo(BreakpointConfigurationPanel.java:76)
	at com.intellij.xdebugger.impl.breakpoints.ui.XLightBreakpointPropertiesPanel.saveProperties(XLightBreakpointPropertiesPanel.java:245)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointItem.saveState(XBreakpointItem.java:97)
	at com.intellij.xdebugger.impl.breakpoints.ui.BreakpointsDialog.b(BreakpointsDialog.java:458)
	at com.intellij.xdebugger.impl.breakpoints.ui.BreakpointsDialog.access$400(BreakpointsDialog.java:65)
	at com.intellij.xdebugger.impl.breakpoints.ui.BreakpointsDialog$3.selectionChangedImpl(BreakpointsDialog.java:239)
	at com.intellij.xdebugger.impl.breakpoints.ui.tree.BreakpointItemsTreeController.selectionChanged(BreakpointItemsTreeController.java:77)
	at com.intellij.xdebugger.impl.breakpoints.ui.tree.BreakpointItemsTreeController$1.valueChanged(BreakpointItemsTreeController.java:66)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:643)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at javax.swing.JTree.setSelectionPath(JTree.java:1634)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3548)
	at com.intellij.util.ui.MouseEventAdapter.mousePressed(MouseEventAdapter.java:42)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Throw file name: BreakpointConfigurationPanel.java
Throw line number: 232
Throw class name: com.google.cloud.tools.intellij.debugger.ui.BreakpointConfigurationPanel
Throw method name: saveTo
Package Information
Package name: com.google.gct.idea
Process name: Cloud Tools for IntelliJ
Package version name: 2016.2 EAP
Installer package name: Cloud Tools for IntelliJ

**Comment by chanseokoh** [comment]
The error that the method `getAllChildren()` doesn't exist [at this code location](https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/c96db042358b7256fd7e7429e3735300ce0a5e92/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/debugger/ui/BreakpointConfigurationPanel.java#L232) (old commit) in the binary at run-time, which cannot ever happen under normal circumstances. (It works perfectly now as well as at the commit where this error happened.) The method is even our code that is being called in the same class. (That is, a caller method in a class cannot find its sibling method.)

Perhaps this happened after the package renaming in the commit c96db042358b7256fd7e7429e3735300ce0a5e92 or a similar event. In any case, I think it is a transient error due to the nature of NoSuchMethodError in this situation.
