### ISSUE TITLE
User reported HttpResponseException on google sign in - 2016.2.1

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#814]
Exception class name: com.google.api.client.http.HttpResponseException: 500 Internal Server Error
 Internal Error
Exception message: Could not parse email after Google service sign-in: 500 Internal Server Error
 Internal Error
Stack trace:
com.google.api.client.http.HttpResponseException: 500 Internal Server Error
Internal Error
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
    at com.google.gdt.eclipse.login.common.GoogleLoginState.queryEmail(GoogleLoginState.java:507)
    at com.google.gdt.eclipse.login.common.GoogleLoginState.updateUserCredentials(GoogleLoginState.java:419)
    at com.google.gdt.eclipse.login.common.GoogleLoginState.logInWithLocalServer(GoogleLoginState.java:359)
    at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$1.run(IntellijGoogleLoginService.java:199)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:556)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by chanseokoh** [comment]
The location of the error is [here](https://github.com/GoogleCloudPlatform/ide-login/blob/master/src/main/java/com/google/cloud/tools/ide/login/GoogleLoginState.java#L500). (However, the GitHub code isn't identical to the code being used in our IntelliJ plugin — they are roughly same.)

The error is a 500 backend error from an HTTP request at that location. Although the fault is at the backend in principle, it'd be worth looking into why this can happen under which situation.

**Comment by etanshaul** [comment]
obsolete
