### ISSUE TITLE
Warn user if using Java 8 with an App Engine Standard project

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#847]

**Comment by patflynn** [comment]
I think this bit me because I had an old version of the dev appserver
bad runtime process port ['']

Sep 22, 2016 2:05:12 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
Sep 22, 2016 2:05:12 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Sep 22, 2016 2:05:12 PM com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction apply
SEVERE: Failed to start server
java.lang.RuntimeException: Unable to restore the previous TimeZone
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.restoreLocalTimeZone(DevAppServer2Impl.java:341)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:244)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)
Caused by: java.lang.NoSuchMethodException: java.util.TimeZone.setDefaultInAppContext(java.util.TimeZone)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.restoreLocalTimeZone(DevAppServer2Impl.java:337)
	... 11 more

**Comment by etanshaul** [comment]
Is the priority for this correctly reflected in the GA milestone? If so we
can prioritize it.

**Comment by patflynn** [comment]
Yeah, if they have Java 8 language level set by default (which they most
likely will), then their standard app configuration is effectively broken.

**Comment by aslo** [comment]
@patflynn How should we handle this, given that java 8 support is coming to EA soon? (see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/946)

**Comment by patflynn** [comment]
Ideally we'd inspect the appengine-web.xml to check the runtime and show
the warning if they're not using 8.

**Comment by patflynn** [comment]
I think we should just check language level. Not JDK. Hopefully the next
SDK release will solve the jdk 8/devappserver issue, and I wouldn't want to
force user to use jdk7 after that's fixed.

**Comment by aslo** [comment]
Just to make sure I understand the desired behavior (please confirm if I have this right)

```
if project language level == 8 
  if appengine-web.xml contains <runtime>java8</runtime>
    do nothing
  else 
    display warning notification to add <runtime>java8</runtime> to their appengine-web.xml
    highlight the problem in appengine-web.xml (warning level)
```

**Comment by patflynn** [comment]
I don't think we can suggest to use <runtime>java8</runtime> for now.
That's not going to be available to most users for some time.

**Comment by aslo** [comment]
Ok, makes sense. So then something like: 

```
if project language level == 8 
  if appengine-web.xml contains <runtime>java8</runtime>
    do nothing
  else 
    display warning notification that java8 is unsupported 
```

**Comment by loosebazooka** [comment]
So the devappserver problem is solved by doing some shenanigans with system properties..
```
-Dappengine.user.timezone=UTC
```
which you can do on the jvmFlags parameter of the RunConfiguration... perhaps this can just be done in the common lib though (we've been doing it in maven/[gradle](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/src/main/java/com/google/cloud/tools/gradle/appengine/AppEngineStandardPlugin.java#L115)).

**Comment by patflynn** [comment]
@loosebazooka you're thinking about a different issue.  The latest breakage
is jsp compiler related.

**Comment by aslo** [comment]
One more question - does this apply to compat as well? Or do we just want to alert users trying to use java8 on AE standard?

**Comment by patflynn** [comment]
That's a fair point.  I guess if <vm>true</vm> or <env>flex</env> we
shouldn't show the warning either.
