### ISSUE TITLE
Crash report - new project wizard?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-intellij#963]
```
java.lang.AssertionError
    at com.intellij.openapi.roots.impl.RootModelImpl.addLibraryEntry(RootModelImpl.java:228)
    at com.google.cloud.tools.intellij.appengine.facet.impl.AppEngineUltimateWebIntegration.addDevServerToModuleDependencies(AppEngineUltimateWebIntegration.java:132)
    at com.google.cloud.tools.intellij.appengine.facet.AppEngineSupportProvider.addSupport(AppEngineSupportProvider.java:147)
    at com.google.cloud.tools.intellij.appengine.facet.AppEngineSupportProvider.access$300(AppEngineSupportProvider.java:74)
    at com.google.cloud.tools.intellij.appengine.facet.AppEngineSupportProvider$AppEngineSupportConfigurable.addSupport(AppEngineSupportProvider.java:247)
    at com.intellij.ide.util.newProjectWizard.AddSupportForFrameworksPanel.addSupport(AddSupportForFrameworksPanel.java:467)
    at com.intellij.ide.projectWizard.ProjectTypeStep$8.update(ProjectTypeStep.java:209)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:266)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.createModule(ModuleBuilder.java:257)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:295)
    at com.intellij.ide.util.projectWizard.ModuleBuilder$3.compute(ModuleBuilder.java:344)
    at com.intellij.ide.util.projectWizard.ModuleBuilder$3.compute(ModuleBuilder.java:341)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:922)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:341)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:327)
    at com.intellij.ide.util.projectWizard.JavaModuleBuilder.commit(JavaModuleBuilder.java:174)
    at com.intellij.ide.impl.NewProjectUtil.a(NewProjectUtil.java:149)
    at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
    at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:71)
    at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:31)
    at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:66)
    at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:145)
    at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:79)
    at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:328)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Description:
null

Device Model:
unknown

Device Release:
2016.2.4

App Version:
2016.2.4

Category Id:
8590668228
Product Specific Data (whitelisted):
app.name.version: IntelliJ IDEA
app.version.major: 2016
app.version.minor: 2.4
java.version: 1.8.0_112-release
java.vm.vendor: JetBrains s.r.o
os.name: Mac OS X
plugin.version: 1.0-BETA-0.2

**Comment by etanshaul** [comment]
Was this from a user report?

**Comment by chanseokoh** [comment]
I think so. We've got an automated email.

**Comment by etanshaul** [comment]
This is strange. This is an exception I was getting in the process of implementing https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/916 (and have since fixed prior to merging the PR). I wonder is somehow this was getting reported even it was during development.

**Comment by chanseokoh** [comment]
FYI, the report was submitted at 2016-10-07 11:51 UTC, which is 7:51 ET today.

**Comment by etanshaul** [comment]
obsolete
