### ISSUE TITLE
AssertionException on loading a project

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#999]
Steps to reproduce: 
1. Create a new app engine standard project (non java EE) via the wizard
2. Close the project and reopen. 
3. Observe "IDE Error Occurred" error notification

Note that this error occurs intermittently, so you may have to repeat a few times to reproduce.

Full stack trace: 

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 42,4,Idea Thread Group] 307463712
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.2.4#IU-162.2032.8 IDEA, eap:false, os:Mac OS X 10.11.6, java-version:JetBrains s.r.o 1.8.0_112-release-b343,6,main] 723421106
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:943)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:690)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:827)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:905)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:787)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:92)
	at com.google.cloud.tools.intellij.appengine.project.DefaultAppEngineAssetProvider.loadAppEngineStandardWebXml(DefaultAppEngineAssetProvider.java:64)
	at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.findAppEngineModulesUsingUnsupportedLanguageLevel(AppEngineStandardUnsupportedJavaVersionCheck.java:78)
	at com.google.cloud.tools.intellij.startup.AppEngineStandardUnsupportedJavaVersionCheck.runActivity(AppEngineStandardUnsupportedJavaVersionCheck.java:63)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:146)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:342)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:160)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:158)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:160)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:153)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.b(ProjectManagerImpl.java:339)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:353)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:413)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:402)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:548)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aslo** [comment]
This can be consistently reproduced by opening the `appengine-web.xml` file in a project, then closing and reopening the project. This makes sense, since the issue is caused by multiple threads contending for read access to that file.
